import java.io.FileWriter;
import java.util.Scanner;

public class MyFile {
    
    public static boolean flag = true;
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);

        while (flag){
            String commandLine = scanner.nextLine();
            if(commandLine.equals("exit")) exit();
            else if(commandLine.contains("ls")) listDirectory("random");
            else if(commandLine.contains("ls_py")) listDirectory("random");
            else if(commandLine.contains("is_dir")) listDirectory("random");
            else if(commandLine.contains("define")) listDirectory("random");
            else if(commandLine.contains("readmod")) listDirectory("random");
            else if(commandLine.contains("setmod")) listDirectory("random");
            else if(commandLine.contains("cat")) listDirectory("random");
            else if(commandLine.contains("append")) listDirectory("random");
            else if(commandLine.contains("bc")) listDirectory("random");
            else if(commandLine.contains("greplong")) listDirectory("random");
            else if(commandLine.equals("help")) help();
            else System.out.println("Wrong command. Please try to write -> help for more options");
        }

    }
    // выводит список всех файлов и директорий для `path` - ls
    public static void listDirectory(String path) {}
    // выводит список файлов с расширением `.py` в `path` - ls_py
    public static void listPythonFiles(String path) {}
    // выводит `true`, если `path` это директория, в других случаях `false` - id_dir
    public static void isDirectory(String path) {}
    // выводит `директория` или `файл` в зависимости от типа `path` - define
    public static void define(String path) {}
    // выводит права для файла в формате `rwx` для текущего пользователя - readmod
    public static void printPermissions(String path) {}
    // устанавливает права для файла `path` - setmod
    public static void setPermissions(String path, String permissions) {}
    // выводит контент файла - cat
    public static void printContent(String path) {}
    // добавляет строке `# Autogenerated line` в конец `path` - append
    public static void appendFooter(String path) {}
    // создает копию `path` в директорию `/tmp/${date}.backup` где, date - это дата в формате `dd-mm-yyyy`. `path`
    // может быть директорией или файлом. При директории, копируется весь контент. - bc
    public static void createBackup(String path) {}
    // выводит самое длинное слово в файле - greplong
    public static void printLongestWord(String path) {}

    // выводит список команд и их описание - help
    public static void help() {
        System.out.println("ls <path>               выводит список всех файлов и директорий для `path`\n" +
                "ls_py <path>            выводит список файлов с расширением `.py` в `path`\n" +
                "is_dir <path>           выводит `true`, если `path` это директория, в других случаях `false`\n" +
                "define <path>           выводит `директория` или `файл` в зависимости от типа `path`\n" +
                "readmod <path>          выводит права для файла в формате `rwx` для текущего пользователя\n" +
                "setmod <path> <perm>    устанавливает права для файла `path`\n" +
                "cat <path>              выводит контент файла\n" +
                "append <path>           добавляет строку `# Autogenerated line` в конец `path`\n" +
                "bc <path>               создает копию `path` в директорию `/tmp/${date}.backup` где, date - это дата в формате `dd-mm-yyyy`\n" +
                "greplong <path>         выводит самое длинное слово в файле\n" +
                "help                    выводит список команд и их описание\n" +
                "exit                    завершает работу программы");
    }

    // завершает работу программы - exit
    public static void exit() {
        flag = false;
    }
}
